import { Product } from '../types';

export const DEMO_PRODUCTS: Product[] = [
    { 
        id: 'prod-1', 
        name: 'Solomillo de Ternera',
        description: 'Corte de primera calidad, ideal para plancha o asado.',
        reference: 'CAR-VAC-001',
        family: 'CAR',
        category: 'VAC',
        iva: 10,
        unit: 'kg', 
        suppliers: [
            { supplierId: 'supplier-1', price: 25.50, status: 'Activo' }, 
            { supplierId: 'supplier-4', price: 28.00, status: 'Inactivo' }
        ],
        status: 'Activo',
        productState: 'Fresco',
        warehouseStatus: 'Bajo Pedido',
        allergens: [],
    },
    { 
        id: 'prod-2', 
        name: 'Pechuga de Pollo',
        description: 'Pechuga de pollo de corral fileteada.',
        reference: 'CAR-AVE-001',
        family: 'CAR',
        category: 'AVE',
        iva: 10,
        unit: 'kg', 
        suppliers: [{ supplierId: 'supplier-1', price: 7.20, status: 'Activo' }],
        status: 'Activo',
        productState: 'Fresco',
        warehouseStatus: 'Disponible',
        allergens: [],
    },
    { 
        id: 'prod-3', 
        name: 'Tomate pera',
        description: 'Tomate de la huerta murciana.',
        reference: 'VER-HOR-001',
        family: 'VER',
        category: 'HOR',
        iva: 4,
        unit: 'kg', 
        suppliers: [{ supplierId: 'supplier-2', price: 1.80, status: 'Activo' }],
        status: 'Activo',
        productState: 'Fresco',
        warehouseStatus: 'Disponible',
        allergens: [],
    },
    { 
        id: 'prod-4', 
        name: 'Lechuga Iceberg',
        description: '',
        reference: 'VER-HOJ-001',
        family: 'VER',
        category: 'HOJ',
        iva: 4,
        unit: 'unidad', 
        suppliers: [{ supplierId: 'supplier-2', price: 0.90, status: 'Activo' }],
        status: 'Activo',
        productState: 'Fresco',
        warehouseStatus: 'Disponible',
        allergens: [],
    },
    { 
        id: 'prod-5', 
        name: 'Harina de Fuerza',
        description: 'Harina de trigo de alta proteína (W300).',
        reference: 'PAN-HAR-001',
        family: 'PAN',
        category: 'HAR',
        iva: 4,
        unit: 'kg', 
        suppliers: [
            { supplierId: 'supplier-3', price: 1.10, status: 'Activo' }, 
            { supplierId: 'supplier-4', price: 1.25, status: 'Activo' }
        ],
        status: 'Activo',
        productState: 'No perecedero',
        warehouseStatus: 'Disponible',
        allergens: ['Gluten'],
    },
    { 
        id: 'prod-6', 
        name: 'Levadura Fresca',
        description: 'Tacos de levadura fresca de panadero.',
        reference: 'PAN-LEV-001',
        family: 'PAN',
        category: 'LEV',
        iva: 10,
        unit: 'paquete', 
        suppliers: [{ supplierId: 'supplier-3', price: 0.50, status: 'Activo' }],
        status: 'Activo',
        productState: 'Fresco',
        warehouseStatus: 'Disponible',
        allergens: [],
    },
    { 
        id: 'prod-7', 
        name: 'Aceite de Oliva Virgen Extra',
        description: 'Garrafa de 5 litros, 0.4º acidez.',
        reference: 'ACE-AOV-001',
        family: 'ACE',
        category: 'AOV',
        iva: 10,
        unit: 'litro', 
        suppliers: [{ supplierId: 'supplier-4', price: 8.50, status: 'Inactivo' }],
        status: 'Activo',
        productState: 'No perecedero',
        warehouseStatus: 'Disponible',
        allergens: [],
    },
    { 
        id: 'prod-8', 
        name: 'Sal Fina',
        description: 'Paquete de sal fina de mesa.',
        reference: 'ESP-CON-001',
        family: 'ESP',
        category: 'CON',
        iva: 21,
        unit: 'kg', 
        suppliers: [{ supplierId: 'supplier-4', price: 0.40, status: 'Activo' }],
        status: 'Inactivo',
        productState: 'No perecedero',
        warehouseStatus: 'Descontinuado',
        allergens: [],
    },
    {
        id: 'prod-9',
        name: 'Salmón Fresco',
        description: 'Lomos de salmón fresco sin espinas.',
        reference: 'PES-PES-001',
        family: 'PES',
        category: 'PES',
        iva: 10,
        unit: 'kg',
        suppliers: [],
        status: 'Activo',
        productState: 'Fresco',
        warehouseStatus: 'Bajo Pedido',
        allergens: ['Pescado'],
    },
    {
        id: 'prod-10',
        name: 'Almejas en Conserva',
        description: 'Lata de almejas al natural.',
        reference: 'PES-MOL-001',
        family: 'PES',
        category: 'MOL',
        iva: 10,
        unit: 'lata',
        suppliers: [],
        status: 'Activo',
        productState: 'Conservas',
        warehouseStatus: 'Disponible',
        allergens: ['Moluscos'],
    }
];