import { Supplier } from '../types';

export const DEMO_SUPPLIERS: Supplier[] = [
    {
        id: 'supplier-1',
        name: 'Distribuciones Cárnicas S.L.',
        cif: 'B12345678',
        address: 'Pol. Ind. Oeste, Calle Principal, 1, 30169 San Ginés, Murcia',
        contactPerson: 'Juan Carnicero',
        phone: '968112233',
        email: 'pedidos@carnicas.com',
        website: 'www.carnicasdist.com',
        notes: 'Realizar pedidos con 48h de antelación. Reparto Martes y Jueves.',
        status: 'Activo',
        avatar: 'https://picsum.photos/seed/carnicas/200/200',
    },
    {
        id: 'supplier-2',
        name: 'Frutas y Verduras del Segura',
        cif: 'B87654321',
        address: 'MercaMurcia, Puesto 12-14, 30120 El Palmar, Murcia',
        contactPerson: 'María Huerta',
        phone: '968445566',
        email: 'info@fvsegura.es',
        website: 'www.fvsegura.es',
        notes: 'Reparto diario excepto Domingos.',
        status: 'Activo',
        avatar: 'https://picsum.photos/seed/fvsegura/200/200',
    },
    {
        id: 'supplier-3',
        name: 'Panadería La Tahona',
        cif: 'G11223344',
        address: 'Calle Mayor, 5, 30001 Murcia',
        contactPerson: 'Pedro Panadero',
        phone: '968778899',
        email: 'latahona@pan.com',
        website: 'www.tahona.es',
        notes: 'Pedidos de panadería y bollería especial con 24h de antelación.',
        status: 'Activo',
        avatar: 'https://picsum.photos/seed/tahona/200/200',
    },
    {
        id: 'supplier-4',
        name: 'Makro',
        cif: 'A55667788',
        address: 'Av. del Rocío, 1, 30169 San Ginés, Murcia',
        contactPerson: 'Atención al Cliente',
        phone: '902101101',
        email: 'atencioncliente@makro.es',
        website: 'www.makro.es',
        notes: 'Proveedor generalista para secos y no perecederos.',
        status: 'Inactivo',
        avatar: 'https://picsum.photos/seed/makro/200/200',
    }
];